### ISSUE TITLE
Linking error

### ISSUE THREAD

**Issue by GrischaJJ** [urbanairship/xamarin-component#18]
Hi,

we get the following error when executing your sample 1) with the wrapper project provided 2) with the xamarin component from the component store:

/Users/grischajacobs/Downloads/xamarin-component-master/samples/ios-unified/MTOUCH: Error MT5211: Native linking failed, undefined Objective-C class: UAWalletAction. The symbol '_OBJC_CLASS_$_UAWalletAction' could not be found in any of the libraries or frameworks linked with your application. (MT5211) (Sample)

/Users/grischajacobs/Downloads/xamarin-component-master/samples/ios-unified/MTOUCH: Error MT5202: Native linking failed. Please review the build log. (MT5202) (Sample)

Please provide fast feedback as we will decide whether to use your tool or not, today.

**Comment by albertoms** [comment]
I'm facing the same issue. It occurs when I try to run app on device; on simulator works fine.

**Comment by GrischaJJ** [comment]
I commented out the Wallet Action class in the wrapper project and it worked properly. Can you please update the nuget package and xamarin component?

**Comment by rlepinski** [comment]
Thanks for pointing this out. We will patch it today.

**Comment by rlepinski** [comment]
Fixed in 2.2.1. Nuget package is updated. Xamarin component is submitted but usually takes a few days to get approved.

**Comment by GrischaJJ** [comment]
I don't see a new nuget package available. 

https://www.nuget.org/packages/urbanairship/
Last update: 3. June 2016

**Comment by albertoms** [comment]
@GrischaJJ finally the update is available. Apparently NuGet takes up to 5 days to show a package update.

**Comment by rlepinski** [comment]
@albertoms @GrischaJJ -  It was our mistake. We did not finish the upload process when publishing the nuget package. Nuget is basically instant.
