### ISSUE TITLE
MTOUCH: error MT3001: Could not AOT the assembly

### ISSUE THREAD

**Issue by johnosullivan** [urbanairship/xamarin-component#20]
Hello, 

I'm currently running the urban airship component on Xamarin.iOS. It builds fine on the Simulator but will fail when building for my device launch. Any would be great thank you!

MTOUCH: error MT3001: Could not AOT the assembly '/Users/johnosullivan/Desktop/Git_PocketCoach/PocketCoach/PocketCoach/iOS/obj/iPhone/Debug/mtouch-cache/64/Build/AirshipBindings.dll'

**Comment by rlepinski** [comment]
Looks like this could be a Xamarin issue. Could you try cleaning your build - https://forums.xamarin.com/discussion/9402/could-not-aot-the-assembly-mt3001 and report back? Also try the latest version of the component.

**Comment by keshavkaul** [comment]
I'm facing this issue after i added the component. On simulator, its building fine, but i'm facing this issue on an iPad mini. Even after restarting IDE this issue still persists.
**Device Build Config**
![device-build-config](https://cloud.githubusercontent.com/assets/3319809/19518758/700aed66-9626-11e6-8f1a-f0b7ca69ed07.png)
**Simulator Build Config**
![simulator-build-config](https://cloud.githubusercontent.com/assets/3319809/19518759/700e1a36-9626-11e6-97dd-7215e12b462e.png)

**Comment by keshavkaul** [comment]
Issue resolved by removing xamarin component and adding the nuget package.

**Comment by keshavkaul** [comment]
I have finally resolved this issue by unchecking incremental builds as advised here https://forums.xamarin.com/discussion/9402/could-not-aot-the-assembly-mt3001

Though this is just a workaround.

**Comment by rlepinski** [comment]
@keshavkaul I am not sure if this is an issue with Xamarin, local cache, or the component. Its weird to me that its not happening on the simulator. Have you tried manually deleting the bin and obj directory?

**Comment by keshavkaul** [comment]
@rlepinski I initially added xamarin component version 3.1.0, which added `urbanairship` nuget package version 3.0.0 automatically. I then encountered this problem. 
Afterwards, i updated the nuget package to 3.1.0 and re-added xamarin component, then this error went away but upon running the app on device i encountered issue #35 . 
So for now, i'm using xamarin component version 3.1.0 with nuget package version 3.0.0 with incremental build unchecked for phone in debug mode which is working well.
