### ISSUE TITLE
Issues with 2.2.1

### ISSUE THREAD

**Issue by littlefyr** [urbanairship/xamarin-component#22]
I updated to 2.2.1 for both ios and Android and I think the component is missing something. 

First of all, the AirshipBindings dll is not put into the list of references. I can add the dll manually  but `NotificationActionButton` is not available.

![screen shot](https://cloud.githubusercontent.com/assets/17768/16966821/2f43638e-4dbb-11e6-98c3-f250bedb1d66.png)

**Comment by rlepinski** [comment]
2.2.2 fixes the issue
