### ISSUE TITLE
Implement iOS10 compatibility

### ISSUE THREAD

**Issue by micronax** [urbanairship/xamarin-component#24]
Currently the Xamarin component seems to be not compatible with iOS10. The app is unable to register as client.

**Comment by rlepinski** [comment]
@micronax We are working on updating our component. Hopefully we will be done with it by next week, but we have been running into issues. Ill let you know as soon as its ready.

**Comment by rlepinski** [comment]
@micronax 3.0.0 version of the component is out. Its going through the review process for Xamarins component store, but the nuget package is published. We are looking into adding the notification service extension support in the next release.
