### ISSUE TITLE
v3.0 breaks iphone-simulator build

### ISSUE THREAD

**Issue by OliverWelther** [urbanairship/xamarin-component#31]
Hi,

I've recently upgraded the UA Xamarin iOS component to v3.0 for iOS 10 support. 
After the upgrade, I can no longer build my iOS App for iPhone simulator. Builds for real devices work though.

Here's the build error. It looks like your binding is missing some symbols for x86.
> MTOUCH: error MT5214: Native linking failed, undefined symbol: _UALocationEventSessionIDKey. This symbol was referenced by the managed member UrbanAirship.Constants.UALocationEventSessionIDKey. Please verify that all the necessary frameworks have been referenced and native libraries linked.
> MTOUCH: error MT5202: Native linking failed. Please review the build log.

The build log shows this error:
> 		Undefined symbols for architecture i386:
> 		  "_UALocationEventSessionIDKey", referenced from:
> 		     -u command line option
> 		ld: symbol(s) not found for architecture i386

Steps to reproduce:
 - create a new iOS project
 - add UA component (v3)
 - call any UA Api function, like UAirship.TakeOff()
 - try to build for iPhone simulator

I'm not 100% sure this if this is an issue with your binding. 
It might also be a Xamarin bug or an issue with my setup, but v2.2.2 worked fine for me.
I'm on Xamarin iOS 10.0.1.10

**Comment by rlepinski** [comment]
@OliverWelther Ill try to reproduce today

**Comment by rlepinski** [comment]
@OliverWelther I was able to reproduce the same issue with a fresh project. I was able to get it building by going to Project options ->iOS Build -> Linker Behavior and setting it to either Link All or Link Framework SDKs only. 

Trying to figure why disabling the linker would do anything. Ill report back with any findings.

**Comment by OliverWelther** [comment]
@rlepinski thanks for your quick response! 
I can confirm that "Link Framework SDK only" works for me. I'll use it as workaround until it's fixed.

**Comment by rlepinski** [comment]
@OliverWelther It appears the field `UALocationEventSessionIDKey` is an undefined extern constant that is never actually used. By enabling the linker it must be stripping it away before Xamarin verifies that its defined. 

We will remove bindings for that field in the next release and remove that constant from the SDK. 

Thanks!
