### ISSUE TITLE
Dyld Error Message: Library not loaded

### ISSUE THREAD

**Issue by keshavkaul** [urbanairship/xamarin-component#35]
@marc-scig @rlepinski 
Getting the following error when deploying which crashes the app.
```
Dyld Error Message:
Dyld Message: Library not loaded: /System/Library/Frameworks/UserNotifications.framework/UserNotifications
  Referenced from: /private/var/containers/Bundle/Application/B6FB66F7-2D65-408A-9EC0-BB0CE5731EBA/Demo.app/Frameworks/AirshipAppExtensions.framework/AirshipAppExtensions
  Reason: image not found
  Dyld Version: 390.7

```
Seems like a ios 10 compatiblity issue. But my deployment target is 9.3 and my device ios is 9.3

**Comment by rlepinski** [comment]
@keshavkaul You need to set the base SDK to 10. You can do that in Xamarin studio by right clicking the project -> Options -> iOS Build -> SDK version. Make sure its set to 10.

**Comment by keshavkaul** [comment]
@rlepinski All members in our team don't have xcode 8 installed hence i cannot explicity add ios 10 as sdk version. Also even after setting sdk version to 10, the problem didn't get solved.

**Comment by rlepinski** [comment]
@keshavkaul 3.0+ requires building with iOS 10. Not sure why 3.1 would cause this issue and not 3.0, its the same underlying SDK. We did change 3.1 to build with a framework instead of a static library. 

When you switched the SDK Version to 10, did you do a clean and rebuild?

**Comment by rlepinski** [comment]
@keshavkaul I was able to reproduce the issue, working on a fix.

**Comment by rlepinski** [comment]
@keshavkaul Nuget package updated to 3.1.1, submitted a component but it takes a few days to publish. You can remove the component and just use the nuget packages directly. 

Thanks for reporting the issue.
