### ISSUE TITLE
Custom Autopilot class not found

### ISSUE THREAD

**Issue by albertoms** [urbanairship/xamarin-component#37]
My Xamarin.Forms app cannot find the custom Autopilot class that I created for the Android project.

This is the metadata that I added to AndroidManifest.xml:

`<meta-data android:name="com.urbanairship.autopilot"
          android:value="myapp.droid.providers.UACustomAutopilot" />`

My class is defined this way:
```
namespace MyApp.Droid.Providers
{
    public class UACustomAutopilot : Autopilot
    {
         public UACustomAutopilot() : base ()
        {
            Log.Info (Constants.LogTag.Push, "UACustomAutopilot()");
        }

        public override void OnAirshipReady (UAirship p0)
        {
            Log.Info (Constants.LogTag.Push, "OnAirshipReady()");
            UAirship.Shared ().PushManager.UserNotificationsEnabled = Settings.Current.PushNotificationsEnabled;
        }

        public override AirshipConfigOptions CreateAirshipConfigOptions (Android.Content.Context p0)
        {
            Log.Info (Constants.LogTag.Push, "CreateAirshipConfigOptions()");
            AirshipConfigOptions options = new AirshipConfigOptions.Builder ()
                                                                   .SetInProduction (Constants.PushDefaults.InProduction)
                                                                   .SetChannelCreationDelayEnabled (true)
                                                                   .Build ();

            return options;
        }
    }
}
```

but Android LogCat said:
`Error (8687) / Urban Airship Autopilot: Class not found: myapp.droid.providers.UACustomAutopilot`

I tried changing the metadata value in many different ways but nothing seems to work.

**Comment by rlepinski** [comment]
I actually do not know how to specify the c# class for autopilot. Ill have to play around with a sample app to figure it out. 

You can workaround this right now by calling takeOff in a custom application during onCreate.

**Comment by rlepinski** [comment]
Looks like java wrapper classes use a generated package name since [5.0.0.](https://developer.xamarin.com/releases/android/xamarin.android_5/xamarin.android_5.0/#Android_Callable_Wrapper_Naming):

> With the 5.0 release, the default package names for Android Callable Wrappers will be based on the MD5SUM of the assembly-qualified name of the type being exported. This allows the same fully-qualified name to be provided from two different assemblies and not get a packaging error.

You can control the fully qualified class name by using RegisterAttribute annotation above the autopilot class:

```
    [RegisterAttribute("myapp.droid.providers.UACustomAutopilot")]
    [Preserve(AllMembers = true)]
    public class UACustomAutopilot : Autopilot
```

Then your manifest entry should work properly.

**Comment by albertoms** [comment]
Thank you, @rlepinski. That solved this issue and many others.
