### ISSUE TITLE
Channel ID opt-in set to false after app update

### ISSUE THREAD

**Issue by albertoms** [urbanairship/xamarin-component#38]
Tested with Xamarin.Forms Android project.

Everytime I change something in the code, stop Xamarin studio and run again to upload new changes, the channel object previously registered is set to false for some reason:
```
        "installed": false,
        "opt_in": false,
        "background": false,
```

I checked this using the API call:
https://go.urbanairship.com/api/named_users/?id=my_named_user

This causes I have to clear the app data in order to create another channel. The previous channel also keeps the association with this named user.

Is there any way to avoid setting to false the channel options everytime I upload new changes from Xamarin studio unless I uninstall the app?

**Comment by rlepinski** [comment]
@albertoms Do you have verbose logging that you can provide? You can enable verbose logging in the airshipconfig.properties with `developmentLogLevel  = VERBOSE` 

These kind of questions are usually best for our support team, if you don't mind could you also post your issue in the support forum? https://support.urbanairship.com/hc/en-us/community/topics

**Comment by albertoms** [comment]
I don't mind, but before that I'm running tests using the option `ClearNamedUser` set to true only in development mode. I'm using a custom autopilot class with the `CreateAirshipConfigOptions()` overriden method. It seems that this setting solves the issue but I cannot confirm it yet.

**Comment by rlepinski** [comment]
@albertoms I assume everything is working? If not please reopen this issue.

**Comment by albertoms** [comment]
Yes. The solution previously mentioned solved the issue :)
