### ISSUE TITLE
No way to access custom keys?

### ISSUE THREAD

**Issue by bhazen** [urbanairship/xamarin-component#53]
In the Android portion of a Xamarin forms project I'm overriding the OnNotificationOpened event like so:
```
public class NotificationReceiver : AirshipReceiver
{
    protected override bool OnNotificationOpened(Context androidContext, NotificationInfo notificationInfo)
    {
        var notificationId = notificationInfo.NotificationId;
        var alert = notificationInfo.Message.Alert;
        var title = notificationInfo.Message.Title;

        return true;
    }
}
```

In the messages I'm sending I'm including some additional data as custom keys.  I expected to find a property for those on the `notificationInfo.Message` object, but I don't see the custom keys anywhere.  Have I just missed where that data is passed or is there currently not a way to access custom keys from the message?

**Comment by rlepinski** [comment]
@bhazen You can access the original push bundle with `notificationInfo.Message.PushBundle` - http://docs.urbanairship.com/reference/libraries/android/latest/reference/com/urbanairship/push/PushMessage.html#getPushBundle()

**Comment by bhazen** [comment]
Thanks, @rlepinski!  That was what I needed.  Was able to do: `var desiredValue = notificationInfo.Message.PushBundle.GetString("key");`
