### ISSUE TITLE
Rich Notifications

### ISSUE THREAD

**Issue by JaridKG** [urbanairship/xamarin-component#76]
Does this component have support for the rich notifications (on iOS 10+)?

Or is their a separate component for that pod?

**Comment by rlepinski** [comment]
Yep, we support it. We have a [nuget](https://www.nuget.org/packages/urbanairship.appextensions/) package that contains the `UAMediaAttachmentExtension` class that you will need to extend in your notification service extension.

**Comment by JaridKG** [comment]
Awesome thanks!

**Comment by JaridKG** [comment]
@rlepinski do you have any documentation or samples for Xamarin of that other package? I implemented it, and created a new provisioning profile for it, but its still not working. Not sure what I'm doing wrong

**Comment by rlepinski** [comment]
@JaridKG Are you able to debug inside the notification service extension? If not, could you try to grab device logs Xcode -> Window -> Devices & Simulators -> Select Device. Send a push and search for your extension name in the output. Apple will usually log something about why the extension could not be started. Here are the docs for native service extension - https://docs.urbanairship.com/platform/reference/ios-extension/

**Comment by BrianBatchelder** [comment]
@JaridKG I was able to extend our sample app to add a working notification service extension. Here are the steps:

1. Follow the [Xamarin directions](https://developer.xamarin.com/guides/ios/platform_features/user-notifications/enhanced-user-notifications/#Implementing_a_Service_Extension) to create your service extension. Don't worry about the code yet.
2. Make sure your service extension's bundle id is formatted as indicated in Xamarin's note on that page (basically, it must start with the app's bundle id).
3. Make sure the service extension's deployment target is iOS 10 or later.
4. Add the urbanairship.appextensions [nuget package](https://www.nuget.org/packages/urbanairship.appextensions/) to your service extension.
5. Replace the generated NotificationService.cs with the following code:

```using Foundation;
using AirshipAppExtensions;

namespace SampleServiceExtension
{
    [Register("NotificationService")]
    public class NotificationService : UAMediaAttachmentExtension
    {
    }
}
```

This should get your service extension working. If it doesn't, please respond with as much detail about the issue as you can.

**Comment by rlepinski** [comment]
@JaridKG An example now lives in the repo. Please contact support if you continue to have issues.
