### ISSUE TITLE
Xamarin.Forms - Android Push Notifications not arriving after every new build.

### ISSUE THREAD

**Issue by Arsophia** [urbanairship/xamarin-component#77]
Hi, This issue is detailed in the following links and was already closed, however, the fix suggested in [https://github.com/urbanairship/xamarin-component/issues/60](url) and in [https://github.com/urbanairship/xamarin-component/issues/43](url) does not work with the current versions of Xamarin. Below more information:

Notifications are not received after new build. In the Urban Airship portal, the device appears in red color for INSTALLED and OPTED IN after every new build, deploying to Android 7.1, with fast deploy enabled, multidex on and the IDE is Visual Studio for Mac. Latest package versions for Xamarin Forms 2.4.0.282, Android Support Libraries 25.4.02 and Urban Airship Nuget 4.6.1.

The only fix I have for now is cleaning the application data on every rebuild, however, as my App have a high security logging system, running through it every build can be a pain as you can imagine.

Any guide will be helpful, maybe it is something about a new packet version?

Thanks!

**Comment by rlepinski** [comment]
@Arsophia Thanks for reporting the issue. We will take a look. It might be an issue upstream with Xamarin.

**Comment by daspuru** [comment]
@rlepinski Thanks to you for your fast reply. I am now finding that the only option I have for now is to totally uninstall de App in the device and then build and deploy again, cleaning the data and cache is not awakening the channel activation upon app start using normal build-deploy cycle.

Thanks a lot.

**Comment by rlepinski** [comment]
https://developer.xamarin.com/guides/android/application_fundamentals/notifications/remote-notifications-with-fcm/#FirebaseApp_is_not_Initialized

> In some cases, you may see this error message:
> 
> Java.Lang.IllegalStateException: Default FirebaseApp is not initialized in this process 
> Make sure to call FirebaseApp.initializeApp(Context) first.
> 
> This is a known problem that you can work around by cleaning the solution and rebuilding the project (Build > Clean Solution, Build > Rebuild Solution). For more information, see this forum discussion.
> 

I believe its the same known issue with Xamarin. We have to use FCM for Android, so if FCM has an issue then we will not be able to receive push notifications. Still looking into it
