### ISSUE TITLE
UADefaultMessageCenterMessageViewController Doesn't Expose Parent's InitWithNib

### ISSUE THREAD

**Issue by benfrye** [urbanairship/xamarin-component#83]
`UADefaultMessageCenterMessageViewController` doesn't provide an extension of the initializer that takes a nib name and NSBundle (`UADefaultMessageCenterMessageViewController(string nibName, NSBundle bundle)`). My main issue is I'm trying to customize the Message Center list view more than is provided through the documented styling. This requires me to roll my own Message Center list view. In order to do that I need a way to display the actual message view. I am attempting to do my own UISplitViewController implementation (as we don't want this to modally present in the app), however, I can't get the `UADefaultMessageCenterMessageViewController` to load properly. In Objective-C land, loading the nib from the UAirship bundle has worked. Unfortunately that initializer has not been exposed in the binding library.  Furthermore, it appears that `UADefaultMessageCenterMessageViewController` has been [deprecated](https://docs.urbanairship.com/reference/libraries/ios/latest/Classes/UADefaultMessageCenterMessageViewController.html) and we should be using `UAMessageCenterMessageViewController` now, however that hasn't been exposed in the binding library yet either.

**Comment by benfrye** [comment]
An alternative could be to just use my own UIWebView but it appears that the message body URL provided needs authentication that is generated by the SDK. Is there a way to access that authentication information?

**Comment by BrianBatchelder** [comment]
@benfrye - we'll look into this, soon.

**Comment by rlepinski** [comment]
@benfrye We will try to have our bindings updated by the end of the week that exposes the methods you need. If you want to attempt it yourself, you need to supply basic auth from the UAUser object https://github.com/urbanairship/xamarin-component/blob/master/src/AirshipBindings.iOS/ApiDefinition.cs#L2767

**Comment by benfrye** [comment]
@rlepinski Where do these credentials come from? I was sniffing the packets being sent by the SDK and I don't recognize the username/password used by the SDK.

**Comment by rlepinski** [comment]
@benfrye we generate the password during the first run. If you have an inbox message you will have a user.

**Comment by BrianBatchelder** [comment]
@benfrye Just released 4.6.4, which should expose the bindings you need. We appreciate your feedback, and plan to expose more of our iOS SDK in our next major release.
