### ISSUE TITLE
Changing NamedUser Identifier Doesn't Call API

### ISSUE THREAD

**Issue by benfrye** [urbanairship/xamarin-component#87]
We are associating `NamedUser` with an internal identifier for targeting specific users, however, once we've set a `NamedUser` identifier it appears to be unchangeable until the app is closed and reopened. We would like to set this at log in, and swap it out with another user should they switch accounts.

Furthermore, messages sent to a `NamedUser`, once on the device, don't appear to have a way of validating that it is the `NamedUser` fetching said messages. I don't see any info on the message either indicating that it's a `NamedUser` and to which `NamedUser` it should go. This means if a user gets messages, logs out, logs into another account, they will see the messages for the first `NamedUser`

**Comment by rlepinski** [comment]
@benfrye Its fully expected for the named user to change mid run. Could you provide logs of your app changing the named user? 

For the inbox being tied to the named user, thats currently not a supported feature. Writing into support requesting that feature is your best bet to get it prioritized. For a workaround you could add the named user as an extra for the message, then filter out the users messages on the device.
